<%-- <div class="nav__toggle nav__toggle--menu show-for-small hide-for-medium">

	<div class="nav__link nav__link--{$DarkLight}"><i class="fa fa-lg fa-bars" aria-hidden="true"></i><span class="nav__menu-text">Menu</span></div>
</div> --%> <%--       <a class="cd-primary-nav-trigger" href="#0">
        <span class="cd-menu-text">Menu</span><span class="cd-menu-icon"></span>
      </a> --%> <div class="nav__toggle nav__toggle--menu show-for-small hide-for-medium"><div class="nav__link nav__link--{$DarkLight} nav__link--mobile-toggle"><span class="nav__menu-icon nav__menu-icon--{$DarkLight}" id="nav__menu-icon"></span><span class="nav__menu-text nav__menu-text--{$DarkLight}" id="nav__menu-text">Menu</span></div></div> <%-- <div class="mobile-nav__wrapper" id="mobile-nav__wrapper">
	<nav class="mobile-nav" aria-label="Main menu">
		<div class="nav__mobile-header show-for-small hide-for-medium"><h1 class="nav__mobile-headtext">$SiteConfig.Title</h1></div>
		<ul class="mobile-nav__list">
			<% loop $Menu(1) %> <li class="nav__item"><a href="$Link" class="nav__link nav__link--mobile">$MenuTitle</a></li> <% end_loop %> <li class="nav__item nav__search-item" id="nav__search-item"><div class="nav__link nav__link--mobile nav__link--search"><span>Search</span> <i class="fa fa-lg fa-search site-search-button" aria-hidden="true"></i></div></li>--%><div class="nav__wrapper nav__wrapper--{$HeaderType} nav__wrapper--{$DarkLight}" id="nav__wrapper"> <%-- <div class="nav__mobile-close-button"><i class="fa fa-lg fa-close site-search__cancel-button" aria-hidden="true"></i></div> --%> <nav role="nav" class="" aria-label="Main menu"><ul class="nav nav--{$DarkLight} nav--{$HeaderType} clearfix" id="nav"> <% loop $Menu(1) %> <li class="nav__item nav__item--{$Top.DarkLight} <% if $FirstLast %>nav__item--$FirstLast<% end_if %><% if $Children %> nav__item--parent<% end_if %> nav__item--{$LinkOrCurrent} nav__item--{$LinkOrSection}"><a class="nav__link nav__link--{$Top.DarkLight}<% if $Children %> nav__link--parent<% end_if %>" href="$Link">$MenuTitle</a> <% if $Children %> <% if $Children.Count > 4 %> <ul class="subnav subnav--{$Top.DarkLight} subnav--two-columns"> <% loop $Children %> <li class="subnav__item subnav__item--column <% if $FirstLast %>subnav__item--$FirstLast<% end_if %>"><a class="subnav__link subnav__link--{$Top.DarkLight}" href="$Link">$MenuTitle.LimitCharacters(30)</a></li> <% end_loop %> </ul> <% else %> <ul class="subnav subnav--{$Top.DarkLight}"> <% loop $Children %> <li class="subnav__item <% if $FirstLast %>subnav__item--$FirstLast<% end_if %>"><a class="subnav__link subnav__link--{$Top.DarkLight}" href="$Link">$MenuTitle</a></li> <% end_loop %> </ul> <% end_if %> <button aria-hidden="true" class="second-level--open"><svg class="dropdownarrow" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14.4 8.8"><path d="M12.8,0l1.6,1.6L7.2,8.8,0,1.6,1.7,0,7.3,5.6Z" transform="translate(0 0)"></path></svg></button> <% end_if %> </li> <% end_loop %> <li class="nav__item nav__item--{$DarkLight} nav__search-item" id="nav__search-item"><div class="nav__link nav__link--{$DarkLight} nav__link--search"><i class="fa fa-lg fa-search site-search-button" aria-hidden="true"></i></div></li> <% include SiteSearch %> </ul></nav></div><div class="nav__toggle nav__toggle--search show-for-small hide-for-medium"><div class="nav__link nav__link--{$DarkLight}"><i class="fa fa-lg fa-search site-search-button" aria-hidden="true"></i></div></div>